version: "3.7"
services:
  db_dev:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: true_to_size_dev
    ports:
      - "5432:5432"
  web:
    build: .
    container_name: tts-web
    volumes:
      - .:/usr/src/app
    depends_on:
      - db_dev
    ports:
      - "3000:3000"